### ISSUE TITLE
Set up the development workflow for the project

### ISSUE THREAD

**Issue by stefanbucur** [googleinterns/bazel-rules-fuzzing#1]
Make sure code reviews are required, and that we have basic presubmit checks using Travis.

**Comment by asraa** [comment]
Basic presubmits on github actions runners:
https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

As far as it seems, you can create files like `.github/workflows/action.yml` to trigger on commits.

**Comment by stefanbucur** [comment]
Make sure to set up branch protection or have the CODEOWNERS file protect us from accidentally directly pushing to the repo.

**Comment by tengpengli** [comment]
Since we already set the branch protection, do I need to add CODEOWNERS file?

**Comment by stefanbucur** [comment]
That's a good point, @tengpengli. Let's skip the CODEOWNERS part then!

**Comment by asraa** [comment]
The CODEOWNERs will automatically assign reviewers, but not sure if it matters since the number of PRs will be small
