### ISSUE TITLE
Enable Starlark language linting in pushes and pull requests

### ISSUE THREAD

**Issue by stefanbucur** [googleinterns/bazel-rules-fuzzing#10]

**Comment by tengpengli** [comment]
Is it the right direction that setting up github actions for downloading skylint and running skylint to do Starlark linting?

**Comment by stefanbucur** [comment]
I would guess so, but I'm deferring this decision to @asraa - I think she knows best this part of the infrastructure.

**Comment by asraa** [comment]
We use only Buildifier for both .bzl files and BUILD files (I think you can? https://github.com/bazelbuild/buildtools/tree/master/buildifier). But yes, a GitHub workflow works. 
I suppose you could also buildifier on BUILDs and skylint on any *.bzl.
`buildifier -mode=check $(find . -type f \( -name BUILD.bazel -or -name BUILD \)`

I recently also learned you can filter actions workflow to only trigger on certain paths, this might be helpful here
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by stefanbucur** [comment]
> I recently also learned you can filter actions workflow to only trigger on certain paths, this might be helpful here
> https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

Oh, that's really nice! @tengpengli, in that case can you also make sure the C++ linter only runs on C++ files (.h, .cc, .cpp)?

**Comment by tengpengli** [comment]
Sounds great to me! I will look into it
