### ISSUE TITLE
Implement a fuzzing dictionary validation tool

### ISSUE THREAD

**Issue by stefanbucur** [googleinterns/bazel-rules-fuzzing#15]
We should use Python for the tool. We should assume AFL & libFuzzer's dictionary format, as documented here:
 * The general dictionary format: https://github.com/rc0r/afl-fuzz/tree/master/dictionaries.
 * The libFuzzer [implementation of dictionary parsing](https://github.com/llvm/llvm-project/blob/6c67ee0f58323fe39db84635ef8cea629c2214b4/compiler-rt/lib/fuzzer/FuzzerUtil.cpp#L127), which only extracts the words between quotes in each dictionary line. We can implement the parser as a regular expression.

We should also add a few tests for the tool, which parse a few sample dictionary files.

**Comment by tengpengli** [comment]
Can you answer a few questions in my mind:
1. Is the rules for afl dictionary the same as libfuzzer's? The desciption of the format in the [afl dictionary](https://github.com/rc0r/afl-fuzz/tree/master/dictionaries) looks the same with libfuzzer to me.
1. If the answer to the first question is no, how can I decide the dictionary file is for afl or libfuzzer? Should the user claim it explicitly?
2. Are the examples listed [here](https://llvm.org/docs/LibFuzzer.html#dictionaries) enough to be the libfuzzer dictionary test cases?
3. As far as I can see from the [libfuzzer code](https://github.com/llvm/llvm-project/blob/6c67ee0f58323fe39db84635ef8cea629c2214b4/compiler-rt/lib/fuzzer/FuzzerUtil.cpp#L81), the name is allowed to be anything excepts quote, but from the given examples, they only contain letters, digits, and underscores, do I get it correctly?

**Comment by stefanbucur** [comment]
> Can you answer a few questions in my mind:

Sure, please find below.

> 1. Is the rules for afl dictionary the same as libfuzzer's? The desciption of the format in the [afl dictionary](https://github.com/rc0r/afl-fuzz/tree/master/dictionaries) looks the same with libfuzzer to me.

That is correct. To be more precise, the complete AFL dictionary specification is more elaborate, since each row may define both a key and a value, e.g. `key="value"`, whereas libFuzzer ignores the key and only uses the value as a dictionary entry (e.g., `"value"`). This is why you will see each row in libFuzzer dictionary examples surrounded by quotes.

For the validation tool, I think it will be sufficient to just focus on the value part of the row and skip the key.

> 2. If the answer to the first question is no, how can I decide the dictionary file is for afl or libfuzzer? Should the user claim it explicitly?

We will not, since we will just consider the simpler libFuzzer subset of the dictionary format.

> 3. Are the examples listed [here](https://llvm.org/docs/LibFuzzer.html#dictionaries) enough to be the libfuzzer dictionary test cases?

Yes, that's a good example. @asraa are there any dictionary examples in the Envoy codebase? We might want to make sure our validation works well on those.

> 4. As far as I can see from the [libfuzzer code](https://github.com/llvm/llvm-project/blob/6c67ee0f58323fe39db84635ef8cea629c2214b4/compiler-rt/lib/fuzzer/FuzzerUtil.cpp#L81), the name is allowed to be anything excepts quote, but from the given examples, they only contain letters, digits, and underscores, do I get it correctly?

Indeed - libFuzzer has a lax interpretation of the syntax for everything left of the `=` sign. I think it will be enough for our validation tool to do the same (e.g., match anything until the first `"`, then interpret the dictionary word).

**Comment by asraa** [comment]
Yep, Envoy has one here, but we don't use them extensively yet, and it uses the single value syntax 
https://github.com/envoyproxy/envoy/blob/master/test/fuzz/headers.dict
