### ISSUE TITLE
Set up Travis support that runs Bazel tests at each PR

### ISSUE THREAD

**Issue by stefanbucur** [googleinterns/bazel-rules-fuzzing#3]

**Comment by tengpengli** [comment]
Does Travis mean Travis CI? If yes, is [this tutorial](https://docs.travis-ci.com/user/tutorial/) the good place to check how to fix this issue?

**Comment by tengpengli** [comment]
@stefanbucur

**Comment by tengpengli** [comment]
I closed the three issues.

Happy weekends!
