### ISSUE TITLE
Update the cc_fuzz_test() rule with dictionary support

### ISSUE THREAD

**Issue by stefanbucur** [googleinterns/bazel-rules-fuzzing#43]
The support should include both (a) feeding the merged dictionary file to the fuzz target, for running, and (b) setting up a regression test (maybe a `sh_test`) to fail in case the dictionary file is broken for some reason (invalid format, etc.)

**Comment by tengpengli** [comment]
I am not quite clear about the regression test. Where does that regression test is used? Is it used to test `fuzzing_launcher` with dictionary?

**Comment by tengpengli** [comment]
> we would also need a separate unit test to fail if the dictionary is invalid - basically a separate rule that would just run the dictionary validator tool on the dictionary files specified in the rule.

I am still not clear enough to work. I  thought the `fuzzing_dictionary` is the tool rule to "just run the dictionary validator tool on the dictionary files specified in the rule".

> Make sure CI fails if there is an invalid dictionary file specified.

Do you mean that we need a command (say `bazel build empty_fuzz_test_with_invalid_dict`) that originally would fail the CI test, but now with a script that aims at catching this specific error message, the CI test can confirm that's a target with invalid dict, thus this CI test is passed? 

The thing confuses me here is that if the CI test is failed, then the merge should be blocked, so I guess a script catching the error message is needed to invert the result.

**Comment by stefanbucur** [comment]
Discussed offline to de-prioritize this. But leaving my answers below for the record:

> > we would also need a separate unit test to fail if the dictionary is invalid - basically a separate rule that would just run the dictionary validator tool on the dictionary files specified in the rule.
> 
> I am still not clear enough to work. I thought the `fuzzing_dictionary` is the tool rule to "just run the dictionary validator tool on the dictionary files specified in the rule".

Yes, that is true. We can still depend on the `fuzzing_dictionary` rule instantiation. It's just that we need something that will trigger that rule to build at CI time. That could be the `_run` launcher, or a separate `sh_test` that invokes the dictionary.

> 
> > Make sure CI fails if there is an invalid dictionary file specified.
> 
> Do you mean that we need a command (say `bazel build empty_fuzz_test_with_invalid_dict`) that originally would fail the CI test, but now with a script that aims at catching this specific error message, the CI test can confirm that's a target with invalid dict, thus this CI test is passed?
> 
> The thing confuses me here is that if the CI test is failed, then the merge should be blocked, so I guess a script catching the error message is needed to invert the result.

That's a good point. This is a special type of test called a "failure test": https://docs.bazel.build/versions/master/skylark/testing.html#failure-testing

It needs to be set up specially (basically make sure the failing rule is marked as `manual`, then set up a wrapper test that succeeds when its dependency fails).
